version: '3'

services: 
    back-28dl:
        build: ./back-28dl
        ports:
            - 3001:3001

    front-full:
        build: ./front-full
        ports:
            - 80:80

    back-stargate:
        build: ./back-stargate
        ports:
            - 3002:3002




    # back-magicbus:
    #     build: ./noc-back-magicbus
    #     ports:
    #         - 
    #     networks: 
    #         - magicbus
    #     depends_on: 
    #      - db-magicbus

    # db-magicbus:
    #     image: mongo
    #     ports:
    #         -27017:27017
    #     networks: 
    #         - magicbus
        
